# From Thinking in Java, 2nd Edition
# At http://www.BruceEckel.com
# (c) Bruce Eckel 2000
# Copyright notice in Copyright.txt
# Automatically-generated MAKEFILE 
# For examples in directory .\c08
# using the JDK 1.2 compiler
# Invoke with: make

JVC = javac
JVCFLAGS =
.SUFFIXES : .class .java
.java.class :
	$(JVC) $(JVCFLAGS) $<

all:  \
	Adventure.class \
	InterfaceCollision.class \
	HorrorShow.class \
	Months.class \
	Month2.class \
	RandVals.class \
	TestRandVals.class \
	Parcel1.class \
	Parcel2.class \
	Destination.class \
	Contents.class \
	Parcel3.class \
	Wrapping.class \
	Parcel4.class \
	Parcel5.class \
	Parcel6.class \
	Parcel7.class \
	Parcel8.class \
	Parcel9.class \
	Sequence.class \
	Parcel10.class \
	IInterface.class \
	TestBed.class \
	Parcel11.class \
	InheritInner.class \
	BigEgg.class \
	BigEgg2.class \
	MultiInterfaces.class \
	MultiImplementation.class \
	Callbacks.class \
	GreenhouseControls.class


Adventure.class: Adventure.java
InterfaceCollision.class: InterfaceCollision.java
HorrorShow.class: HorrorShow.java
Months.class: Months.java
Month2.class: Month2.java
RandVals.class: RandVals.java
TestRandVals.class: TestRandVals.java
Parcel1.class: Parcel1.java
Parcel2.class: Parcel2.java
Destination.class: Destination.java
Contents.class: Contents.java
Parcel3.class: Parcel3.java
Wrapping.class: Wrapping.java
Parcel4.class: Parcel4.java
Parcel5.class: Parcel5.java
Parcel6.class: Parcel6.java
Parcel7.class: Parcel7.java
Parcel8.class: Parcel8.java
Parcel9.class: Parcel9.java
Sequence.class: Sequence.java
Parcel10.class: Parcel10.java
IInterface.class: IInterface.java
TestBed.class: TestBed.java
Parcel11.class: Parcel11.java
InheritInner.class: InheritInner.java
BigEgg.class: BigEgg.java
BigEgg2.class: BigEgg2.java
MultiInterfaces.class: MultiInterfaces.java
MultiImplementation.class: MultiImplementation.java
Callbacks.class: Callbacks.java
GreenhouseControls.class: GreenhouseControls.java
